import {
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  Min,
  IsDateString,
  IsObject,
  IsArray,
  ArrayMaxSize,
  IsInt,
  ValidateNested,
  Equals,
  MaxLength,
  MinLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';

class InternalAgentContextEvidenceDto {
  @IsEnum(['QUANT', 'MACRO_NEWS', 'REGIME', 'RISK', 'REFLECTION'])
  source: 'QUANT' | 'MACRO_NEWS' | 'REGIME' | 'RISK' | 'REFLECTION';

  @IsString()
  @MinLength(1)
  @MaxLength(160)
  sourceId: string;

  @IsEnum(['BUY', 'SELL', 'NEUTRAL', 'BLOCK'])
  stance: 'BUY' | 'SELL' | 'NEUTRAL' | 'BLOCK';

  @IsNumber()
  @Min(0)
  @Max(1)
  confidence: number;

  @IsNumber()
  @Min(0)
  @Max(1)
  credibility: number;

  @IsInt()
  @Min(0)
  @Max(100)
  verifiedSources: number;

  @IsDateString()
  availableAt: string;

  @IsString()
  @MinLength(1)
  @MaxLength(500)
  summary: string;
}

class InternalAgentContextDto {
  @Equals('agent-council-v1')
  version: 'agent-council-v1';

  @IsEnum(['ALIGNED', 'CONFLICT', 'INSUFFICIENT', 'BLOCKED'])
  status: 'ALIGNED' | 'CONFLICT' | 'INSUFFICIENT' | 'BLOCKED';

  @IsEnum(['BUY', 'SELL', 'NEUTRAL'])
  consensusDirection: 'BUY' | 'SELL' | 'NEUTRAL';

  @IsNumber()
  @Min(0)
  weightedSupport: number;

  @IsNumber()
  @Min(0)
  weightedOpposition: number;

  @IsNumber()
  @Min(0)
  @Max(1)
  disagreementScore: number;

  @IsInt()
  @Min(0)
  @Max(100)
  evidenceCount: number;

  @IsInt()
  @Min(0)
  rejectedCount: number;

  @IsArray()
  @ArrayMaxSize(10)
  @ValidateNested({ each: true })
  @Type(() => InternalAgentContextEvidenceDto)
  evidence: InternalAgentContextEvidenceDto[];

  @IsEnum(['AVAILABLE', 'UNAVAILABLE', 'NOT_APPLICABLE'])
  sourceState: 'AVAILABLE' | 'UNAVAILABLE' | 'NOT_APPLICABLE';

  @IsDateString()
  evaluatedAt: string;

  @Equals(true)
  advisoryOnly: true;

  @Equals(false)
  executionAuthority: false;
}

/**
 * InternalSignalDto — Request body for the Python AI Engine → NestJS internal signal endpoint.
 *
 * POST /api/v1/ai/internal/signals
 * Protected by: x-irexpro-internal-api-key header (InternalApiKeyGuard)
 * Not accessible via user JWT alone.
 *
 * IMPORTANT: Signals submitted here go through the FULL pipeline:
 *   AiSignalService → Strategy Orchestrator → Risk Engine → Execution Engine → Broker Adapter
 *
 * There is NO shortcut to the broker.
 * Compatible with Python AiSignalCandidate schema (camelCase field names).
 */
export class InternalSignalDto {
  @ApiPropertyOptional({
    description: 'Signal UUID (generated by Python engine)',
    example: 'uuid-v4',
  })
  @IsOptional()
  @IsString()
  signalId?: string;

  @ApiProperty({ description: 'Target user UUID', example: 'uuid-v4' })
  @IsUUID()
  userId: string;

  @ApiProperty({ description: 'Active trading session UUID', example: 'uuid-v4' })
  @IsUUID()
  tradingSessionId: string;

  @ApiProperty({ description: 'Broker connection UUID', example: 'uuid-v4' })
  @IsUUID()
  brokerConnectionId: string;

  @ApiProperty({ description: 'Forex instrument', example: 'EURUSD' })
  @IsString()
  instrument: string;

  @ApiProperty({ enum: ['BUY', 'SELL'] })
  @IsEnum(['BUY', 'SELL'])
  direction: 'BUY' | 'SELL';

  @ApiProperty({ description: 'Model confidence score 0–1', example: 0.75 })
  @IsNumber()
  @Min(0)
  @Max(1)
  confidenceScore: number;

  @ApiPropertyOptional({ description: 'Suggested entry price (null = market order)' })
  @IsOptional()
  @IsNumber()
  suggestedEntryPrice?: number;

  @ApiProperty({ description: 'Stop-loss price' })
  @IsNumber()
  @Min(0)
  suggestedStopLoss: number;

  @ApiProperty({ description: 'Take-profit price' })
  @IsNumber()
  @Min(0)
  suggestedTakeProfit: number;

  @ApiProperty({ description: 'Lot size', example: 0.01 })
  @IsNumber()
  @Min(0.001)
  suggestedVolume: number;

  @ApiProperty({ description: 'Chart timeframe', example: 'H1' })
  @IsString()
  timeframe: string;

  @ApiProperty({ description: 'Strategy code from AI engine', example: 'baseline-h1' })
  @IsString()
  strategyCode: string;

  @ApiPropertyOptional({ description: 'Market regime (trending/ranging/volatile)' })
  @IsOptional()
  @IsString()
  marketRegime?: string;

  @ApiPropertyOptional({ description: 'Volatility score 0–1' })
  @IsOptional()
  @IsNumber()
  @Min(0)
  @Max(1)
  volatilityScore?: number;

  @ApiPropertyOptional({ description: 'Signal generation timestamp (ISO 8601)' })
  @IsOptional()
  @IsDateString()
  generatedAt?: string;

  @ApiProperty({ description: 'AI model version string', example: 'baseline-xgboost-v0.1.0' })
  @IsString()
  modelVersion: string;

  @ApiPropertyOptional({
    description: 'Advisory Agent Council snapshot. Never grants execution authority.',
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => InternalAgentContextDto)
  agentContext?: InternalAgentContextDto | null;

  @ApiPropertyOptional({ description: 'Explainability + audit metadata (no secrets)' })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}
