import {
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  Min,
  IsDateString,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * InternalExitSignalDto — Round 6 live-execution completion (§10): request
 * body for the Python AI Engine → NestJS internal EXIT-signal endpoint.
 *
 * POST /api/v1/ai/internal/exit-signals
 * Protected by: x-irexpro-internal-api-key header (InternalApiKeyGuard)
 * Not accessible via user JWT alone.
 *
 * An exit decision is risk-REDUCING: it routes through the §10 serialized
 * exit orchestrator (session gate → identity gate → per-user serialization
 * → closeTrade with AI_CLOSE_SIGNAL) — it NEVER enters the NEW-exposure
 * pipeline (no risk grant, no sizing, no allocation) and is NEVER a direct
 * broker call.
 */
export class InternalExitSignalDto {
  @ApiPropertyOptional({
    description: 'Exit-decision UUID (generated by Python engine when omitted)',
    example: 'uuid-v4',
  })
  @IsOptional()
  @IsString()
  signalId?: string;

  @ApiProperty({ description: 'Target user UUID', example: 'uuid-v4' })
  @IsUUID()
  userId: string;

  @ApiProperty({ description: 'Active trading session UUID', example: 'uuid-v4' })
  @IsUUID()
  tradingSessionId: string;

  @ApiProperty({ description: 'Forex instrument to exit', example: 'EURUSD' })
  @IsString()
  instrument: string;

  @ApiPropertyOptional({
    description:
      'Close exactly this trade (open position id). Omit to flatten EVERY open position on the instrument.',
  })
  @IsOptional()
  @IsUUID()
  tradeId?: string;

  @ApiProperty({ description: 'Model confidence score 0–1 (same threshold as entries)', example: 0.8 })
  @IsNumber()
  @Min(0)
  @Max(1)
  confidenceScore: number;

  @ApiPropertyOptional({ description: 'Exit-decision generation timestamp (ISO 8601)' })
  @IsOptional()
  @IsDateString()
  generatedAt?: string;

  @ApiPropertyOptional({ description: 'Strategy provenance (audit + identity digest material)' })
  @IsOptional()
  @IsString()
  strategyCode?: string;

  @ApiPropertyOptional({ description: 'Model provenance (audit + identity digest material)' })
  @IsOptional()
  @IsString()
  modelVersion?: string;

  @ApiPropertyOptional({ description: 'Free-text rationale (audit only)' })
  @IsOptional()
  @IsString()
  rationale?: string;
}
