"""Robustness diagnostics for frozen research candidates.

This module deliberately does not change model selection or promotion gates.
It audits whether headline trading statistics have enough evidence to be
interpreted confidently and provides probabilistic Sharpe diagnostics.
"""
from __future__ import annotations

import math
from collections.abc import Iterable
from dataclasses import dataclass
from statistics import NormalDist

import numpy as np

EULER_MASCHERONI = 0.5772156649015329


@dataclass(frozen=True)
class EvidenceAssessment:
    trade_count: int
    minimum_trade_count: int
    preferred_trade_count: int
    sufficient_for_inference: bool
    preferred_evidence_reached: bool
    warning: str | None


def assess_trade_evidence(
    trade_count: int,
    *,
    minimum_trade_count: int = 30,
    preferred_trade_count: int = 100,
) -> EvidenceAssessment:
    """Classify evidence volume without altering any existing research gate."""
    if trade_count < 0:
        raise ValueError("trade_count cannot be negative")
    if minimum_trade_count < 2:
        raise ValueError("minimum_trade_count must be at least 2")
    if preferred_trade_count < minimum_trade_count:
        raise ValueError("preferred_trade_count must be >= minimum_trade_count")

    sufficient = trade_count >= minimum_trade_count
    preferred = trade_count >= preferred_trade_count
    warning = None
    if not sufficient:
        warning = (
            f"Only {trade_count} active trades are available; headline Sharpe, "
            "profit factor, and drawdown are statistically fragile."
        )
    elif not preferred:
        warning = (
            f"{trade_count} active trades exceed the minimum audit floor but "
            "remain below the preferred evidence volume."
        )
    return EvidenceAssessment(
        trade_count=trade_count,
        minimum_trade_count=minimum_trade_count,
        preferred_trade_count=preferred_trade_count,
        sufficient_for_inference=sufficient,
        preferred_evidence_reached=preferred,
        warning=warning,
    )


def _sample_moments(returns: Iterable[float]) -> tuple[np.ndarray, float, float]:
    values = np.asarray(list(returns), dtype=float)
    if values.size < 3:
        raise ValueError("at least three returns are required")
    if not np.isfinite(values).all():
        raise ValueError("returns contain non-finite values")
    centered = values - values.mean()
    std = values.std(ddof=1)
    if std <= 0:
        raise ValueError("returns require non-zero sample variance")
    m2 = float(np.mean(centered**2))
    m3 = float(np.mean(centered**3))
    m4 = float(np.mean(centered**4))
    skewness = m3 / (m2 ** 1.5) if m2 > 0 else 0.0
    kurtosis = m4 / (m2 * m2) if m2 > 0 else 3.0
    return values, float(skewness), float(kurtosis)


def probabilistic_sharpe_ratio(
    returns: Iterable[float],
    *,
    benchmark_sharpe: float = 0.0,
) -> dict[str, float]:
    """Bailey/Lopez de Prado PSR using the unannualized sample Sharpe.

    The benchmark must use the same return frequency as the input returns.
    """
    values, skewness, kurtosis = _sample_moments(returns)
    sharpe = float(values.mean() / values.std(ddof=1))
    denominator_term = (
        1.0
        - skewness * sharpe
        + ((kurtosis - 1.0) / 4.0) * (sharpe**2)
    )
    if denominator_term <= 0:
        raise ValueError("PSR denominator is not positive")
    z_score = (
        (sharpe - benchmark_sharpe)
        * math.sqrt(values.size - 1)
        / math.sqrt(denominator_term)
    )
    probability = NormalDist().cdf(z_score)
    return {
        "sample_count": float(values.size),
        "sample_sharpe_unannualized": sharpe,
        "benchmark_sharpe_unannualized": float(benchmark_sharpe),
        "skewness": skewness,
        "kurtosis": kurtosis,
        "z_score": float(z_score),
        "probabilistic_sharpe_ratio": float(probability),
    }


def expected_maximum_sharpe(
    trial_sharpes: Iterable[float],
) -> dict[str, float]:
    """Estimate the expected best Sharpe generated by multiple trials.

    Trial Sharpes must be comparable and use the same annualization convention.
    """
    values = np.asarray(list(trial_sharpes), dtype=float)
    if values.size < 2:
        raise ValueError("at least two comparable trial Sharpes are required")
    if not np.isfinite(values).all():
        raise ValueError("trial_sharpes contain non-finite values")
    sigma = float(values.std(ddof=1))
    mean = float(values.mean())
    if sigma == 0.0:
        return {
            "trial_count": float(values.size),
            "trial_sharpe_mean": mean,
            "trial_sharpe_std": 0.0,
            "expected_maximum_sharpe": mean,
        }

    normal = NormalDist()
    n = float(values.size)
    z1 = normal.inv_cdf(1.0 - 1.0 / n)
    z2 = normal.inv_cdf(1.0 - 1.0 / (n * math.e))
    expected = mean + sigma * (
        (1.0 - EULER_MASCHERONI) * z1
        + EULER_MASCHERONI * z2
    )
    return {
        "trial_count": n,
        "trial_sharpe_mean": mean,
        "trial_sharpe_std": sigma,
        "expected_maximum_sharpe": float(expected),
    }


def robustness_snapshot(
    returns: Iterable[float],
    *,
    minimum_trade_count: int = 30,
    preferred_trade_count: int = 100,
    comparable_trial_sharpes: Iterable[float] | None = None,
) -> dict[str, object]:
    """Build a fail-honest statistical robustness snapshot.

    DSR is intentionally not fabricated when a complete comparable trial
    history is unavailable. The expected-maximum Sharpe component is emitted
    only when the caller supplies such a ledger.
    """
    values = np.asarray(list(returns), dtype=float)
    evidence = assess_trade_evidence(
        int(values.size),
        minimum_trade_count=minimum_trade_count,
        preferred_trade_count=preferred_trade_count,
    )
    payload: dict[str, object] = {
        "evidence": {
            "trade_count": evidence.trade_count,
            "minimum_trade_count": evidence.minimum_trade_count,
            "preferred_trade_count": evidence.preferred_trade_count,
            "sufficient_for_inference": evidence.sufficient_for_inference,
            "preferred_evidence_reached": evidence.preferred_evidence_reached,
            "warning": evidence.warning,
        },
        "psr": probabilistic_sharpe_ratio(values) if values.size >= 3 else None,
        "multiple_testing": {
            "status": "TRIAL_LEDGER_REQUIRED",
            "expected_maximum_sharpe": None,
        },
    }
    if comparable_trial_sharpes is not None:
        payload["multiple_testing"] = {
            "status": "PARTIAL_OR_COMPLETE_LEDGER_SUPPLIED",
            **expected_maximum_sharpe(comparable_trial_sharpes),
        }
    return payload
